---
- name: build image and push to docker hub play
  hosts: ansible_host
  tasks:
  - name: remove image
    command: docker rmi vawote7449/my-hello-world
    ignore_errors: true
  - name: build image
    command: docker build -t vawote7449/my-hello-world ~/hello-world
  #- name: docker login
  #  command: docker login -u <ID> -p <PW>
  - name: push image
    command: docker push vawote7449/my-hello-world
